FROM mysql:8.4

# Set UTF-8 environment
ENV LC_ALL=C.UTF-8 \
    LANG=C.UTF-8

# Copy initialization script
COPY sql/init-entrypoint.sh /usr/local/bin/init-entrypoint.sh
RUN chmod +x /usr/local/bin/init-entrypoint.sh

ENTRYPOINT ["/usr/local/bin/init-entrypoint.sh"]
CMD ["mysqld"]
